event_name: card_binding_pick_type_plastic_submit
description: тут має бути опис події
trigger: trigger
criticality: high
status: draft
documentation_status: complete
platforms:
  ios: true
  android: true
parameters: []
screenshot:
  path: assets/events/card_binding_pick_type_plastic_submit/screenshot.png
  alt: card_binding_pick_type_plastic_submit screen
