event_name: card_binding_pick_type_plastic_submit
description: фівфівфів
trigger: asdasd asd asd as evesea
criticality: medium
status: draft
documentation_status: complete
platforms:
  ios: true
  android: true
parameters:
  - name: type
    type: string
    required: true
    description: ''
screenshot:
  path: assets/events/card_binding_pick_type_plastic_submit/screenshot.png
  alt: card_binding_pick_type_plastic_submit screen
