event_name: cc_details_statement_tap
description: statement tap
trigger: sadasdasd
criticality: medium
status: draft
documentation_status: complete
platforms:
  ios: true
  android: true
parameters: []
screenshot:
  path: assets/events/cc_details_statement_tap/screenshot.png
  alt: cc_details_statement_tap screen
